[package]
name = "chess_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
strum = "0.27.2"
strum_macros = "0.27.2"
eframe = "0.28"
egui = "0.28"
egui_extras = { version = "0.28", features = ["svg"] }
